config = {
    # this should be the directory where rpyvideoserver is installed
    # it will look here for the html files etc
    'run_dir' : '/opt/rpyvideoserver/',

    # directiories where the server will search for movies, subdirectories are searched as well
    'video_dirs' :
    [
        "movies"
    ],

    # extensions for files which the server should consider movies
    'video_extensions' :
    (
        '.mkv',
        '.mp4',
        '.avi'
    ),

    # program and arguments to play movies
    'video_player_cmd' : ['omxplayer', '-o', 'hdmi', '-r', '-y'],

    # video player controls
    'pause' : 'p',
    'small_seek_forward' : '[C',
    'small_seek_backward' : '[D',
    'big_seek_forward' : '[A',
    'big_seek_backward' : '[B',
    'vol+' : '+',
    'vol-' : '-',

    # default no password
    # generated by: `printf "" | sha256sum`
    # replace the empty string with your password and use the hash here
    'password_hash' : 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',

    'http_ip' : "0.0.0.0",
    'http_port' : 8000
}
